@startuml

title __ADAPTER's Class Diagram__\n

  namespace  {
    namespace om.designpatterns.java {
      namespace structural.adapter {
        class com.designpatterns.java.structural.adapter.AdapterPatternDemo {
            {static} + main()
        }
      }
    }
  }
  

  namespace  {
    namespace om.designpatterns.java {
      namespace structural.adapter {
        class com.designpatterns.java.structural.adapter.BankCustomer {
            + getCreditCard()
            + giveBankDetails()
        }
      }
    }
  }
  

  namespace  {
    namespace om.designpatterns.java {
      namespace structural.adapter {
        class com.designpatterns.java.structural.adapter.BankDetails {
            - accHolderName : String
            - accNumber : long
            - bankName : String
            + getAccHolderName()
            + getAccNumber()
            + getBankName()
            + setAccHolderName()
            + setAccNumber()
            + setBankName()
        }
      }
    }
  }
  

  namespace  {
    namespace om.designpatterns.java {
      namespace structural.adapter {
        interface com.designpatterns.java.structural.adapter.CreditCard {
            {abstract} + getCreditCard()
            {abstract} + giveBankDetails()
        }
      }
    }
  }
  

  com.designpatterns.java.structural.adapter.BankCustomer .up.|> com.designpatterns.java.structural.adapter.CreditCard
  com.designpatterns.java.structural.adapter.BankCustomer -up-|> com.designpatterns.java.structural.adapter.BankDetails


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
