@startuml

title __COMPOSITE's Class Diagram__\n

  namespace  {
    namespace om.designpatterns.java {
      namespace structural.composite {
        class com.designpatterns.java.structural.composite.Accountant {
            - id : int
            - name : String
            - salary : double
            + Accountant()
            + add()
            + getChild()
            + getId()
            + getName()
            + getSalary()
            + print()
            + remove()
        }
      }
    }
  }
  

  namespace  {
    namespace om.designpatterns.java {
      namespace structural.composite {
        class com.designpatterns.java.structural.composite.BankManager {
            ~ employees : List<Employee>
            - id : int
            - name : String
            - salary : double
            + BankManager()
            + add()
            + getChild()
            + getId()
            + getName()
            + getSalary()
            + print()
            + remove()
        }
      }
    }
  }
  

  namespace  {
    namespace om.designpatterns.java {
      namespace structural.composite {
        class com.designpatterns.java.structural.composite.Cashier {
            - id : int
            - name : String
            - salary : double
            + Cashier()
            + add()
            + getChild()
            + getId()
            + getName()
            + getSalary()
            + print()
            + remove()
        }
      }
    }
  }
  

  namespace  {
    namespace om.designpatterns.java {
      namespace structural.composite {
        class com.designpatterns.java.structural.composite.CompositePatternDemo {
            {static} + main()
        }
      }
    }
  }
  

  namespace  {
    namespace om.designpatterns.java {
      namespace structural.composite {
        interface com.designpatterns.java.structural.composite.Employee {
            {abstract} + add()
            {abstract} + getChild()
            {abstract} + getId()
            {abstract} + getName()
            {abstract} + getSalary()
            {abstract} + print()
            {abstract} + remove()
        }
      }
    }
  }
  

  com.designpatterns.java.structural.composite.Accountant .up.|> com.designpatterns.java.structural.composite.Employee
  com.designpatterns.java.structural.composite.BankManager .up.|> com.designpatterns.java.structural.composite.Employee
  com.designpatterns.java.structural.composite.Cashier .up.|> com.designpatterns.java.structural.composite.Employee


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
